
# thermostat HC1

- platform: mqtt
  state_topic: 'home/ems-esp/thermostat_data'
  name: 'Current Room Temperature'
  unit_of_measurement: '°C'
  value_template: "{{ value_json.hc1.currtemp }}"

- platform: mqtt
  state_topic: 'home/ems-esp/thermostat_data'
  name: 'Current Set Temperature'
  unit_of_measurement: '°C'
  value_template: "{{ value_json.hc1.seltemp }}" 

- platform: mqtt
  state_topic: 'home/ems-esp/thermostat_data'
  name: 'Current Mode'
  value_template: "{{ value_json.hc1.mode }}" 

  # boiler

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Tap Water'
  value_template: '{{ value_json.tapwaterActive }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Heating'
  value_template: '{{ value_json.heatingActive }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Warm Water selected temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.wWSelTemp }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Warm Water tapwater flow rate'
  unit_of_measurement: 'l/min'
  value_template: '{{ value_json.wWCurFlow }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Warm Water current temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.wWCurTmp }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Warm Water activated'
  value_template: '{{ value_json.wWActivated }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Warm Water 3-way valve'
  value_template: '{{ value_json.wWHeat }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Current flow temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.curFlowTemp }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Return temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.retTemp }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Gas'
  value_template: '{{ value_json.burnGas }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Boiler pump'
  value_template: '{{ value_json.heatPmp }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Fan'
  value_template: '{{ value_json.fanWork }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Ignition'
  value_template: '{{ value_json.ignWork }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Circulation pump'
  value_template: '{{ value_json.wWCirc }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Burner max power'
  unit_of_measurement: '%'
  value_template: '{{ value_json.selBurnPow }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Burner max power'
  unit_of_measurement: '%'
  value_template: '{{ value_json.selBurnPow }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Burner current power'
  unit_of_measurement: '%'
  value_template: '{{ value_json.curBurnPow }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'System Pressure'
  unit_of_measurement: 'bar'
  value_template: '{{ value_json.sysPress }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Boiler temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.boilTemp }}'

- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: 'Pump modulation'
  unit_of_measurement: '%'
  value_template: '{{ value_json.pumpMod }}'

  # shower time duration

- platform: mqtt
  name: 'Last shower duration'
  state_topic: "home/ems-esp/shower_data"
  value_template: "{{ value_json.duration | is_defined }}"

- platform: template
  sensors:
    showertime_time:
      value_template: '{{ as_timestamp(states.sensor.last_shower_duration.last_updated) | int | timestamp_custom("%-I:%M on %a %-d %b") }}'

    boiler_updated:
      value_template: '{{ as_timestamp(states.sensor.boiler_temperature.last_updated) | timestamp_custom("%H:%M on %d/%b") }}'

    boiler_boottime:
      value_template: '{{ as_timestamp(states.automation.see_if_boiler_restarts.attributes.last_triggered) | timestamp_custom("%H:%M:%S %d/%m/%y") }}'

# general

- platform: mqtt
  state_topic: 'home/ems-esp/status'
  name: 'ems-esp status'
