// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Language
	 */
	LANGUAGE: string
	/**
	 * is required
	 */
	IS_REQUIRED: string
	/**
	 * Sign In
	 */
	SIGN_IN: string
	/**
	 * Sign Out
	 */
	SIGN_OUT: string
	/**
	 * Username
	 */
	USERNAME: string
	/**
	 * Password
	 */
	PASSWORD: string
	/**
	 * Dashboard
	 */
	DASHBOARD: string
	/**
	 * Settings
	 */
	SETTINGS: string
	/**
	 * Help
	 */
	HELP: string
	/**
	 * Logged in as {name}
	 * @param {unknown} name
	 */
	LOGGED_IN: RequiredParams<'name'>
	/**
	 * Please sign in to continue
	 */
	PLEASE_SIGNIN: string
	/**
	 * Upload successful
	 */
	UPLOAD_SUCCESSFUL: string
	/**
	 * Invalid login details
	 */
	INVALID_LOGIN: string
	/**
	 * Network Connection
	 */
	NETWORK_CONNECTION: string
	/**
	 * Security
	 */
	SECURITY: string
	/**
	 * Network Time
	 */
	NETWORK_TIME: string
	/**
	 * ON/OFF
	 */
	ONOFF_CAP: string
	/**
	 * on/off
	 */
	ONOFF: string
	/**
	 * Type
	 */
	TYPE: string
	/**
	 * Description
	 */
	DESCRIPTION: string
	/**
	 * Entities
	 */
	ENTITIES: string
	/**
	 * Refresh
	 */
	REFRESH: string
	/**
	 * Export
	 */
	EXPORT: string
	/**
	 * Entity Name
	 */
	ENTITY_NAME: string
	/**
	 * Value
	 */
	VALUE: string
	/**
	 * only show favorites
	 */
	SHOW_FAV: string
	/**
	 * Device and Sensor Data
	 */
	DEVICE_SENSOR_DATA: string
	/**
	 * Devices & Sensors
	 */
	DEVICES_SENSORS: string
	/**
	 * Attached EMS-ESP Sensors
	 */
	ATTACHED_SENSORS: string
	/**
	 * Call Command
	 */
	RUN_COMMAND: string
	/**
	 * Change Value
	 */
	CHANGE_VALUE: string
	/**
	 * Cancel
	 */
	CANCEL: string
	/**
	 * Reset
	 */
	RESET: string
	/**
	 * Send
	 */
	SEND: string
	/**
	 * Save
	 */
	SAVE: string
	/**
	 * Remove
	 */
	REMOVE: string
	/**
	 * Problem updating
	 */
	PROBLEM_UPDATING: string
	/**
	 * Access Denied
	 */
	ACCESS_DENIED: string
	/**
	 * Analog Sensor{post}
	 * @param {unknown} post
	 */
	ANALOG_SENSOR: RequiredParams<'post'>
	/**
	 * Temperature Sensor{post}
	 * @param {unknown} post
	 */
	TEMP_SENSOR: RequiredParams<'post'>
	/**
	 * Write command {cmd}
	 * @param {unknown} cmd
	 */
	WRITE_COMMAND: RequiredParams<'cmd'>
	/**
	 * EMS bus disconnected. If this warning still persists after a few seconds please check settings and board profile
	 */
	EMS_BUS_WARNING: string
	/**
	 * Scanning for EMS devices...
	 */
	EMS_BUS_SCANNING: string
	/**
	 * Connected
	 */
	CONNECTED: string
	/**
	 * Tx issues - try a different Tx Mode
	 */
	TX_ISSUES: string
	/**
	 * Disconnected
	 */
	DISCONNECTED: string
	/**
	 * Scanning for devices...
	 */
	SCANNING: string
	/**
	 * Are you sure you want to initiate a full device scan of the EMS bus?
	 */
	EMS_SCAN: string
	/**
	 * EMS Bus Status
	 */
	EMS_BUS_STATUS: string
	/**
	 * Active Devices & Sensors
	 */
	ACTIVE_DEVICES: string
	/**
	 * Device
	 */
	DEVICE: string
	/**
	 * SUCCESS
	 */
	SUCCESS: string
	/**
	 * FAIL
	 */
	FAIL: string
	/**
	 * QUALITY
	 */
	QUALITY: string
	/**
	 * Scan for new devices
	 */
	SCAN_DEVICES: string
	/**
	 * EMS Bus & Activity Status
	 */
	EMS_BUS_STATUS_TITLE: string
	/**
	 * Scan
	 */
	SCAN: string
	STATUS_NAMES: {
		/**
		 * EMS Telegrams Received (Rx)
		 */
		'0': string
		/**
		 * EMS Reads (Tx)
		 */
		'1': string
		/**
		 * EMS Writes (Tx)
		 */
		'2': string
		/**
		 * Temperature Sensor Reads
		 */
		'3': string
		/**
		 * Analog Sensor Reads
		 */
		'4': string
		/**
		 * MQTT Publishes
		 */
		'5': string
		/**
		 * API Calls
		 */
		'6': string
		/**
		 * Syslog Messages
		 */
		'7': string
	}
}

export type TranslationFunctions = {
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * is required
	 */
	IS_REQUIRED: () => LocalizedString
	/**
	 * Sign In
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign Out
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Dashboard
	 */
	DASHBOARD: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Help
	 */
	HELP: () => LocalizedString
	/**
	 * Logged in as {name}
	 */
	LOGGED_IN: (arg: { name: unknown }) => LocalizedString
	/**
	 * Please sign in to continue
	 */
	PLEASE_SIGNIN: () => LocalizedString
	/**
	 * Upload successful
	 */
	UPLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Invalid login details
	 */
	INVALID_LOGIN: () => LocalizedString
	/**
	 * Network Connection
	 */
	NETWORK_CONNECTION: () => LocalizedString
	/**
	 * Security
	 */
	SECURITY: () => LocalizedString
	/**
	 * Network Time
	 */
	NETWORK_TIME: () => LocalizedString
	/**
	 * ON/OFF
	 */
	ONOFF_CAP: () => LocalizedString
	/**
	 * on/off
	 */
	ONOFF: () => LocalizedString
	/**
	 * Type
	 */
	TYPE: () => LocalizedString
	/**
	 * Description
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * Entities
	 */
	ENTITIES: () => LocalizedString
	/**
	 * Refresh
	 */
	REFRESH: () => LocalizedString
	/**
	 * Export
	 */
	EXPORT: () => LocalizedString
	/**
	 * Entity Name
	 */
	ENTITY_NAME: () => LocalizedString
	/**
	 * Value
	 */
	VALUE: () => LocalizedString
	/**
	 * only show favorites
	 */
	SHOW_FAV: () => LocalizedString
	/**
	 * Device and Sensor Data
	 */
	DEVICE_SENSOR_DATA: () => LocalizedString
	/**
	 * Devices & Sensors
	 */
	DEVICES_SENSORS: () => LocalizedString
	/**
	 * Attached EMS-ESP Sensors
	 */
	ATTACHED_SENSORS: () => LocalizedString
	/**
	 * Call Command
	 */
	RUN_COMMAND: () => LocalizedString
	/**
	 * Change Value
	 */
	CHANGE_VALUE: () => LocalizedString
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Reset
	 */
	RESET: () => LocalizedString
	/**
	 * Send
	 */
	SEND: () => LocalizedString
	/**
	 * Save
	 */
	SAVE: () => LocalizedString
	/**
	 * Remove
	 */
	REMOVE: () => LocalizedString
	/**
	 * Problem updating
	 */
	PROBLEM_UPDATING: () => LocalizedString
	/**
	 * Access Denied
	 */
	ACCESS_DENIED: () => LocalizedString
	/**
	 * Analog Sensor{post}
	 */
	ANALOG_SENSOR: (arg: { post: unknown }) => LocalizedString
	/**
	 * Temperature Sensor{post}
	 */
	TEMP_SENSOR: (arg: { post: unknown }) => LocalizedString
	/**
	 * Write command {cmd}
	 */
	WRITE_COMMAND: (arg: { cmd: unknown }) => LocalizedString
	/**
	 * EMS bus disconnected. If this warning still persists after a few seconds please check settings and board profile
	 */
	EMS_BUS_WARNING: () => LocalizedString
	/**
	 * Scanning for EMS devices...
	 */
	EMS_BUS_SCANNING: () => LocalizedString
	/**
	 * Connected
	 */
	CONNECTED: () => LocalizedString
	/**
	 * Tx issues - try a different Tx Mode
	 */
	TX_ISSUES: () => LocalizedString
	/**
	 * Disconnected
	 */
	DISCONNECTED: () => LocalizedString
	/**
	 * Scanning for devices...
	 */
	SCANNING: () => LocalizedString
	/**
	 * Are you sure you want to initiate a full device scan of the EMS bus?
	 */
	EMS_SCAN: () => LocalizedString
	/**
	 * EMS Bus Status
	 */
	EMS_BUS_STATUS: () => LocalizedString
	/**
	 * Active Devices & Sensors
	 */
	ACTIVE_DEVICES: () => LocalizedString
	/**
	 * Device
	 */
	DEVICE: () => LocalizedString
	/**
	 * SUCCESS
	 */
	SUCCESS: () => LocalizedString
	/**
	 * FAIL
	 */
	FAIL: () => LocalizedString
	/**
	 * QUALITY
	 */
	QUALITY: () => LocalizedString
	/**
	 * Scan for new devices
	 */
	SCAN_DEVICES: () => LocalizedString
	/**
	 * EMS Bus & Activity Status
	 */
	EMS_BUS_STATUS_TITLE: () => LocalizedString
	/**
	 * Scan
	 */
	SCAN: () => LocalizedString
	STATUS_NAMES: {
		/**
		 * EMS Telegrams Received (Rx)
		 */
		'0': () => LocalizedString
		/**
		 * EMS Reads (Tx)
		 */
		'1': () => LocalizedString
		/**
		 * EMS Writes (Tx)
		 */
		'2': () => LocalizedString
		/**
		 * Temperature Sensor Reads
		 */
		'3': () => LocalizedString
		/**
		 * Analog Sensor Reads
		 */
		'4': () => LocalizedString
		/**
		 * MQTT Publishes
		 */
		'5': () => LocalizedString
		/**
		 * API Calls
		 */
		'6': () => LocalizedString
		/**
		 * Syslog Messages
		 */
		'7': () => LocalizedString
	}
}

export type Formatters = {}
