plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
# use these if not using PnP and have node_modules
# compressionLevel: 0
# nmMode: hardlinks-local
# enableGlobalCache: true
