#!/bin/sh

#
# Builds the dump CSV files, modbus headers and documentation.
# To be run before a release with
#   sh ./scripts/generate_csv_and_headers.sh
#

# build dummy modbus_entity_parameters.hpp  so it compiles
cat >./src/modbus_entity_parameters.hpp <<EOL
#include "modbus.h"
#include "emsdevice.h"

/*
 * This file is auto-generated by the update_modbus_registers.sh script. Do not modify.
*/

// clang-format off

namespace emsesp {

using dt = EMSdevice::DeviceType;

#define REGISTER_MAPPING(device_type, device_value_tag_type, long_name, modbus_register_offset, modbus_register_count) \\
    { device_type, device_value_tag_type, long_name[0], modbus_register_offset, modbus_register_count }

// IMPORTANT: This list MUST be ordered by keys "device_type", "device_value_tag_type" and "modbus_register_offset" in this order.
const std::initializer_list<Modbus::EntityModbusInfo> Modbus::modbus_register_mappings = {};

} // namespace emsesp

// clang-format on

EOL

# build emsesp for standalone
make clean
make ARGS=-DEMSESP_STANDALONE

# dump_entities.csv
rm -f dump_entities.csv
echo "test entity_dump" | ./emsesp | python3 ./scripts/strip_csv.py >dump_entities.csv
ls -al dump_entities.csv

# dump_telegrams.csv
rm -f dump_telegrams.csv
echo "test telegram_dump" | ./emsesp | python3 ./scripts/strip_csv.py >dump_telegrams.csv
ls -al dump_telegrams.csv

# generate ./src/modbus_entity_parameters.hpp
rm -f ./src/modbus_entity_parameters.hpp
cat dump_entities.csv | python3 ./scripts/update_modbus_registers.py >./src/modbus_entity_parameters.hpp
ls -al ./src/modbus_entity_parameters.hpp

# generate doc - Modbus-Entity-Registers.md used in the emsesp.org documentation.
cat dump_entities.csv | python3 ./scripts/generate-modbus-register-doc.py >./docs/Modbus-Entity-Registers.md
